batch_size: 2
iters: 80000

train_dataset:
  type: Dataset
  dataset_root: dataset/dlrsd
  train_path: dataset/dlrsd/train.txt
  num_classes: 18
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [256, 256]
    - type: RandomHorizontalFlip
    - type: Normalize
  mode: train


val_dataset:
  type: Dataset
  dataset_root: dataset/dlrsd
  val_path: dataset/dlrsd/val.txt
  num_classes: 18
  transforms:
    - type: Normalize
    - type: Resize
      target_size: [256, 256]
  mode: val


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]
